/**
 * LY.com Inc.
 * Copyright (c) 2004-2016 All Rights Reserved.
 */ 
package groovy.dal.ibatis;

import groovy.dal.operation.tbarsactivityinfo.*;
import groovy.dal.dataobject.*;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.ly.sof.utils.page.PageQuery;
import com.ly.sof.utils.page.PageList;
import com.ly.sof.utils.page.PageQueryUtils;
import org.springframework.dao.DataAccessException;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import groovy.dal.dataobject.TbArsActivityInfoDO;
import groovy.dal.daointerface.TbArsActivityInfoDAO;

/**
 * TbArsActivityInfoDAO
 * database table: tb_ars_activity_info
 * database table comments: TbArsActivityInfo
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class IbatisTbArsActivityInfoDAO extends SqlMapClientDaoSupport implements TbArsActivityInfoDAO {


	/**
	 * 
	 * sql: 
	 * <pre>select         *      from         tb_ars_activity_info      where         id = ?</pre>
	 */
	public TbArsActivityInfoDO findById(Long id) throws DataAccessException {
		return (TbArsActivityInfoDO)getSqlMapClientTemplate().queryForObject("GroovyTest02.TbArsActivityInfo.findById",id);
	}

}

