/**
 * LY.com Inc.
 * Copyright (c) 2004-2016 All Rights Reserved.
 */
package groovy.dal.dataobject;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;


import java.io.*;
import java.net.*;
import java.util.*;

import java.math.BigDecimal;
import java.math.BigInteger;

import com.ly.sof.utils.page.PageQuery;
import com.ly.sof.utils.page.PageList;
import com.ly.sof.utils.page.PageQueryUtils;
/**
 * TbArsActivityInfoDO
 * database table: tb_ars_activity_info
 * database table comments: TbArsActivityInfo
 * This file is generated by <tt>dalgen</tt>, a DAL (Data Access Layer)
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/dalgen</tt>
 * 
 * @author Allen Wang(Wang Junxiang)
 * */
public class TbArsActivityInfoDO implements java.io.Serializable {
	private static final long serialVersionUID = -5216457518046898601L;
	
	/**
	 * 主键id 		db_column: id 
	 */
	private long id;
	/**
	 * 活动结束时间 		db_column: activity_end_time 
	 */
	private long activityEndTime;
	/**
	 * 预热开始时间 		db_column: warmup_start_time 
	 */
	private long warmupStartTime;
	/**
	 * 是否预热 		db_column: has_warmup 
	 */
	private Boolean hasWarmup;
	/**
	 * 申请时间 		db_column: apply_time 
	 */
	private long applyTime;
	/**
	 * 活动开始时间 		db_column: activity_start_time 
	 */
	private long activityStartTime;
	/**
	 * demo url 		db_column: demo_url 
	 */
	private String demoUrl;
	/**
	 * 删除标记 		db_column: deleted 
	 */
	private Boolean deleted;
	/**
	 * 审核备注 		db_column: audit_remark 
	 */
	private String auditRemark;
	/**
	 * 审核人 		db_column: audit_user_id 
	 */
	private long auditUserId;
	/**
	 * 全部类目 		db_column: all_categories 
	 */
	private Boolean allCategories;
	/**
	 * 申请人 		db_column: apply_user_id 
	 */
	private long applyUserId;
	/**
	 * 提报截止时间 		db_column: apply_end_time 
	 */
	private long applyEndTime;
	/**
	 * 提报活动描述 		db_column: description 
	 */
	private String description;
	/**
	 * 提报活动名称 		db_column: name 
	 */
	private String name;
	/**
	 * 活动状态 		db_column: activity_status 
	 */
	private int activityStatus;
	/**
	 * needRepublish 		db_column: need_republish 
	 */
	private Boolean needRepublish;
	/**
	 * 审核时间 		db_column: audit_time 
	 */
	private long auditTime;
	/**
	 * 活动类型 		db_column: activity_type 
	 */
	private int activityType;
	/**
	 * 创建时间 		db_column: db_create_time 
	 */
	private Date dbCreateTime;
	/**
	 * 更新时间 		db_column: db_update_time 
	 */
	private Date dbUpdateTime;
	/**
	 * 是否是已发布的活动修改活动基本信息 		db_column: new_edit_activity_label 
	 */
	private Boolean newEditActivityLabel;
	/**
	 * 活动附件数据，json存储 		db_column: file_info_json 
	 */
	private String fileInfoJson;
	/**
	 * 发布时间 		db_column: PUBLISH_TIME 
	 */
	private long publishTime;
	/**
	 * 活动补充说明 		db_column: ADD_DESCRIPTION 
	 */
	private String addDescription;
	/**
	 * pop招商配置截止时间 		db_column: business_end_time 
	 */
	private long businessEndTime;
	/**
	 * POP报名截止时间 		db_column: sign_up_end_time 
	 */
	private long signUpEndTime;
	/**
	 * 创建人ID 		db_column: create_user_id 
	 */
	private long createUserId;
	/**
	 * 是测试活动，0否 1是 		db_column: is_test_act 
	 */
	private Boolean isTestAct;
	/**
	 * Pop报名开始时间 		db_column: sign_up_start_time 
	 */
	private long signUpStartTime;
	/**
	 * 电子协议 		db_column: agreement 
	 */
	private String agreement;
	/**
	 * 是否默认使用电子协议，0否 1是 		db_column: use_default_agreement 
	 */
	private Boolean useDefaultAgreement;
	/**
	 * 活动详细介绍 		db_column: detail_desc 
	 */
	private String detailDesc;
	/**
	 * 活动报名状态 		db_column: apply_status 
	 */
	private int applyStatus;
	/**
	 * 搭建活动id 		db_column: build_activity_id 
	 */
	private long buildActivityId;
	/**
	 * 活动来源：1-提报系统，2-搭建系统 		db_column: activity_source 
	 */
	private int activitySource;
	/**
	 * 创建人所属分组Id 		db_column: creator_squad_id 
	 */
	private long creatorSquadId;

	
	public void setId(long id) {
		this.id = id;
	}
	
	public long getId() {
		return this.id;
	}
	
	public void setActivityEndTime(long activityEndTime) {
		this.activityEndTime = activityEndTime;
	}
	
	public long getActivityEndTime() {
		return this.activityEndTime;
	}
	
	public void setWarmupStartTime(long warmupStartTime) {
		this.warmupStartTime = warmupStartTime;
	}
	
	public long getWarmupStartTime() {
		return this.warmupStartTime;
	}
	
	public void setHasWarmup(Boolean hasWarmup) {
		this.hasWarmup = hasWarmup;
	}
	
	public Boolean getHasWarmup() {
		return this.hasWarmup;
	}
	
	public void setApplyTime(long applyTime) {
		this.applyTime = applyTime;
	}
	
	public long getApplyTime() {
		return this.applyTime;
	}
	
	public void setActivityStartTime(long activityStartTime) {
		this.activityStartTime = activityStartTime;
	}
	
	public long getActivityStartTime() {
		return this.activityStartTime;
	}
	
	public void setDemoUrl(String demoUrl) {
		this.demoUrl = demoUrl;
	}
	
	public String getDemoUrl() {
		return this.demoUrl;
	}
	
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}
	
	public Boolean getDeleted() {
		return this.deleted;
	}
	
	public void setAuditRemark(String auditRemark) {
		this.auditRemark = auditRemark;
	}
	
	public String getAuditRemark() {
		return this.auditRemark;
	}
	
	public void setAuditUserId(long auditUserId) {
		this.auditUserId = auditUserId;
	}
	
	public long getAuditUserId() {
		return this.auditUserId;
	}
	
	public void setAllCategories(Boolean allCategories) {
		this.allCategories = allCategories;
	}
	
	public Boolean getAllCategories() {
		return this.allCategories;
	}
	
	public void setApplyUserId(long applyUserId) {
		this.applyUserId = applyUserId;
	}
	
	public long getApplyUserId() {
		return this.applyUserId;
	}
	
	public void setApplyEndTime(long applyEndTime) {
		this.applyEndTime = applyEndTime;
	}
	
	public long getApplyEndTime() {
		return this.applyEndTime;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	public String getDescription() {
		return this.description;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public String getName() {
		return this.name;
	}
	
	public void setActivityStatus(int activityStatus) {
		this.activityStatus = activityStatus;
	}
	
	public int getActivityStatus() {
		return this.activityStatus;
	}
	
	public void setNeedRepublish(Boolean needRepublish) {
		this.needRepublish = needRepublish;
	}
	
	public Boolean getNeedRepublish() {
		return this.needRepublish;
	}
	
	public void setAuditTime(long auditTime) {
		this.auditTime = auditTime;
	}
	
	public long getAuditTime() {
		return this.auditTime;
	}
	
	public void setActivityType(int activityType) {
		this.activityType = activityType;
	}
	
	public int getActivityType() {
		return this.activityType;
	}
	
	public void setDbCreateTime(Date dbCreateTime) {
		this.dbCreateTime = dbCreateTime;
	}
	
	public Date getDbCreateTime() {
		return this.dbCreateTime;
	}
	
	public void setDbUpdateTime(Date dbUpdateTime) {
		this.dbUpdateTime = dbUpdateTime;
	}
	
	public Date getDbUpdateTime() {
		return this.dbUpdateTime;
	}
	
	public void setNewEditActivityLabel(Boolean newEditActivityLabel) {
		this.newEditActivityLabel = newEditActivityLabel;
	}
	
	public Boolean getNewEditActivityLabel() {
		return this.newEditActivityLabel;
	}
	
	public void setFileInfoJson(String fileInfoJson) {
		this.fileInfoJson = fileInfoJson;
	}
	
	public String getFileInfoJson() {
		return this.fileInfoJson;
	}
	
	public void setPublishTime(long publishTime) {
		this.publishTime = publishTime;
	}
	
	public long getPublishTime() {
		return this.publishTime;
	}
	
	public void setAddDescription(String addDescription) {
		this.addDescription = addDescription;
	}
	
	public String getAddDescription() {
		return this.addDescription;
	}
	
	public void setBusinessEndTime(long businessEndTime) {
		this.businessEndTime = businessEndTime;
	}
	
	public long getBusinessEndTime() {
		return this.businessEndTime;
	}
	
	public void setSignUpEndTime(long signUpEndTime) {
		this.signUpEndTime = signUpEndTime;
	}
	
	public long getSignUpEndTime() {
		return this.signUpEndTime;
	}
	
	public void setCreateUserId(long createUserId) {
		this.createUserId = createUserId;
	}
	
	public long getCreateUserId() {
		return this.createUserId;
	}
	
	public void setIsTestAct(Boolean isTestAct) {
		this.isTestAct = isTestAct;
	}
	
	public Boolean getIsTestAct() {
		return this.isTestAct;
	}
	
	public void setSignUpStartTime(long signUpStartTime) {
		this.signUpStartTime = signUpStartTime;
	}
	
	public long getSignUpStartTime() {
		return this.signUpStartTime;
	}
	
	public void setAgreement(String agreement) {
		this.agreement = agreement;
	}
	
	public String getAgreement() {
		return this.agreement;
	}
	
	public void setUseDefaultAgreement(Boolean useDefaultAgreement) {
		this.useDefaultAgreement = useDefaultAgreement;
	}
	
	public Boolean getUseDefaultAgreement() {
		return this.useDefaultAgreement;
	}
	
	public void setDetailDesc(String detailDesc) {
		this.detailDesc = detailDesc;
	}
	
	public String getDetailDesc() {
		return this.detailDesc;
	}
	
	public void setApplyStatus(int applyStatus) {
		this.applyStatus = applyStatus;
	}
	
	public int getApplyStatus() {
		return this.applyStatus;
	}
	
	public void setBuildActivityId(long buildActivityId) {
		this.buildActivityId = buildActivityId;
	}
	
	public long getBuildActivityId() {
		return this.buildActivityId;
	}
	
	public void setActivitySource(int activitySource) {
		this.activitySource = activitySource;
	}
	
	public int getActivitySource() {
		return this.activitySource;
	}
	
	public void setCreatorSquadId(long creatorSquadId) {
		this.creatorSquadId = creatorSquadId;
	}
	
	public long getCreatorSquadId() {
		return this.creatorSquadId;
	}

	public String toString() {
		return new ToStringBuilder(this)
			.append("Id",getId())
			.append("ActivityEndTime",getActivityEndTime())
			.append("WarmupStartTime",getWarmupStartTime())
			.append("HasWarmup",getHasWarmup())
			.append("ApplyTime",getApplyTime())
			.append("ActivityStartTime",getActivityStartTime())
			.append("DemoUrl",getDemoUrl())
			.append("Deleted",getDeleted())
			.append("AuditRemark",getAuditRemark())
			.append("AuditUserId",getAuditUserId())
			.append("AllCategories",getAllCategories())
			.append("ApplyUserId",getApplyUserId())
			.append("ApplyEndTime",getApplyEndTime())
			.append("Description",getDescription())
			.append("Name",getName())
			.append("ActivityStatus",getActivityStatus())
			.append("NeedRepublish",getNeedRepublish())
			.append("AuditTime",getAuditTime())
			.append("ActivityType",getActivityType())
			.append("DbCreateTime",getDbCreateTime())
			.append("DbUpdateTime",getDbUpdateTime())
			.append("NewEditActivityLabel",getNewEditActivityLabel())
			.append("FileInfoJson",getFileInfoJson())
			.append("PublishTime",getPublishTime())
			.append("AddDescription",getAddDescription())
			.append("BusinessEndTime",getBusinessEndTime())
			.append("SignUpEndTime",getSignUpEndTime())
			.append("CreateUserId",getCreateUserId())
			.append("IsTestAct",getIsTestAct())
			.append("SignUpStartTime",getSignUpStartTime())
			.append("Agreement",getAgreement())
			.append("UseDefaultAgreement",getUseDefaultAgreement())
			.append("DetailDesc",getDetailDesc())
			.append("ApplyStatus",getApplyStatus())
			.append("BuildActivityId",getBuildActivityId())
			.append("ActivitySource",getActivitySource())
			.append("CreatorSquadId",getCreatorSquadId())
			.toString();
	}
	
	public int hashCode() {
		return new HashCodeBuilder()
			.append(getId())
			.toHashCode();
	}
	
	public boolean equals(Object obj) {
		if(obj == null) return false;
		if(this == obj) return true;
		if(obj instanceof TbArsActivityInfoDO == false) return false;
		TbArsActivityInfoDO other = (TbArsActivityInfoDO)obj;
		return new EqualsBuilder()
			.append(getId(),other.getId())
			.isEquals();
	}
}

